### PR TITLE
Fix qmake build on macOS

### LINKED ISSUE #2383: Builds fail on macOS
**Describe the bug**

Related to #1328, which fixes it for Travis CI, but not for local builds too:

> I think we should merge this until we can figure out what's actually wrong.

**To reproduce**

https://github.com/Chatterino/chatterino2/blob/master/BUILDING_ON_MAC.md

**Screenshots**

**Chatterino version**

**Operating system**

macOS Big Sur 11.1 (20C69)

**Additional information**

### PR DESCRIPTION
**Pull request by revolter**
Fixes https://github.com/Chatterino/chatterino2/issues/2383.

### CODE REVIEW

**Comment by revolter** [comment]
cc @leon-richardt

**Comment by revolter** [comment]
Apparently, this was already fixed in the upstream: https://github.com/frankosterfeld/qtkeychain/commit/95c6021e280ebe4692e7729cf626c7298db9b226.

Maybe this fork should be synced with the upstream, but you guys know better.

**Comment by leon-richardt** [comment]
AFAIK, the fork only exists because of https://github.com/Chatterino/qtkeychain/commit/832f550da3f6655168a737d2e1b7df37272e936d so syncing with upstream seems like it should be easy enough. Good spot :+1:

@fourtf, @pajlada, thoughts on this?

**Comment by pajlada** [comment]
@revolter Thanks a lot for bringing the upstream changes to our attention - I've gone ahead and brought our fork up-to-date with the upstream repo - there's a PR in the Chatterino2 repo that updates the version used https://github.com/Chatterino/chatterino2/pull/2393

**Pull request closed without merging**
